name: Flutter Build (Web)

on:
  workflow_call:
    inputs:
      publish_branch:
        description: "Target branch to deploy web build artifacts"
        required: true
        type: string
      wasm:
        description: "If passed it will compile for WebAssembly"
        required: false
        type: boolean
    secrets:
      github_x_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web (default)
        if: ${{ !inputs.wasm }}
        run: flutter build web --release
      
      - name: Build web (wasm)
        if: ${{ inputs.wasm }}
        run: flutter build web --release --wasm

      - name: Deploy to target branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.github_x_token }}
          publish_branch: ${{ inputs.publish_branch }}
          publish_dir: ./build/web
          force_orphan: true
